const boards = {
  ondas: 'Cabelo ondulado: leveza e definição',
  cachos: 'Cabelo cacheado: definição e cuidado',
  finalizacao: 'Finalização e day after',
  produtos: 'Produtos para cabelos com curvatura',
};

export const pins = [
  {
    id: '01', kind: 'guide', theme: 'terracotta', compact: true,
    eyebrow: 'CHECKLIST COMPLETO', headline: '8 erros que desmontam as ondas',
    intro: 'Marque o que acontece na sua finalização e mude só um item por lavagem.',
    rows: [
      ['Expectativa de cacho fechado', 'Observe a sua onda natural.'],
      ['Partes quase secas', 'Umedeça antes de aplicar.'],
      ['Creme demais', 'Comece com uma dose menor.'],
      ['Só creme quando falta fixação', 'Teste pouco mousse, gel ou gelatina.'],
      ['Pentear depois de amassar', 'Não desfaça os grupos de ondas.'],
      ['Tocar enquanto seca', 'Espere secar sem manipular.'],
      ['Soltar a camada firme cedo', 'Amasse apenas depois de seco.'],
      ['Trocar tudo de uma vez', 'Mude uma variável por lavagem.'],
    ],
    title: 'Cabelo ondulado não define? Checklist com 8 erros comuns',
    description: 'Os 8 erros são: esperar outro formato natural; finalizar partes quase secas; usar creme demais; depender só do creme quando falta fixação; pentear depois de amassar; tocar durante a secagem; soltar a camada firme cedo; e trocar toda a rotina de uma vez. Salve para conferir na próxima lavagem.',
    alt: 'Checklist vertical enumera oito erros que podem desmontar as ondas e mostra uma correção curta para cada um.',
    required: ['Expectativa de cacho fechado', 'Partes quase secas', 'Creme demais', 'Só creme quando falta fixação', 'Pentear depois de amassar', 'Tocar enquanto seca', 'Soltar a camada firme cedo', 'Trocar tudo de uma vez'],
    cta: 'Salve para a próxima lavagem',
    link: '/artigos/cabelo-ondulado-nao-define-erros/', board: boards.ondas,
    publish: '2026-09-01T12:00:00', local: '01/09/2026 09:00', keywords: 'cabelo ondulado não define, erros finalização ondulada, ondas sem definição, cabelo ondulado',
  },
  {
    id: '02', kind: 'photo', theme: 'plum', photo: '01-separar-mechas.png', side: 'left', position: 'center 58%',
    eyebrow: 'UMIDADE POR IGUAL', headline: 'Uma parte seca antes da outra?',
    body: 'Separe o cabelo em quatro partes e borrife água na seção que secou antes de aplicar mais produto.',
    title: 'Cabelo ondulado seca desigual? Separe antes de finalizar',
    description: 'Divida o cabelo ondulado em quatro partes. Trabalhe uma seção por vez e, se ela secar antes da aplicação, borrife apenas água. Isso ajuda a distribuir o finalizador de forma mais uniforme. Salve para testar na próxima finalização.',
    alt: 'Mulher ondulada de costas divide o cabelo úmido em quatro partes com presilhas antes de finalizar.',
    cta: 'Salve para testar',
    link: '/artigos/cabelo-ondulado-nao-define-erros/', board: boards.ondas,
    publish: '2026-09-01T17:30:00', local: '01/09/2026 14:30', keywords: 'finalização cabelo ondulado, separar cabelo em mechas, cabelo úmido, ondas definidas',
  },
  {
    id: '03', kind: 'guide', theme: 'blue',
    eyebrow: 'TESTE DE 3 LAVAGENS', headline: 'Descubra o que desmonta suas ondas',
    intro: 'Mantenha shampoo e condicionador iguais para comparar uma mudança por vez.',
    rows: [
      ['Lavagem 1', 'Reduza o creme e mantenha a técnica.'],
      ['Lavagem 2', 'Repita a dose e acrescente pouca fixação.'],
      ['Lavagem 3', 'Mantenha os produtos e não toque enquanto seca.'],
      ['Compare', 'Volume, duração, toque e tempo de secagem.'],
    ],
    title: 'Teste de 3 lavagens para o cabelo ondulado definir melhor',
    description: 'Lavagem 1: reduza o creme. Lavagem 2: mantenha a dose e acrescente pouco fixador. Lavagem 3: mantenha os produtos e pare de tocar durante a secagem. Compare volume, duração, toque e tempo de secagem. Salve o roteiro antes de começar.',
    alt: 'Roteiro vertical apresenta três lavagens controladas e quatro critérios para comparar a definição do cabelo ondulado.',
    required: ['Lavagem 1', 'Lavagem 2', 'Lavagem 3', 'Volume, duração, toque e tempo de secagem'],
    cta: 'Salve o roteiro',
    link: '/artigos/cabelo-ondulado-nao-define-erros/', board: boards.ondas,
    publish: '2026-09-01T23:00:00', local: '01/09/2026 20:00', keywords: 'teste cabelo ondulado, finalização ondulada, ondas duram pouco, fixação cabelo',
  },
  {
    id: '04', kind: 'product', theme: 'rose', products: ['widi-ondulando.png', 'salon-line-definicao.png', 'inoar-meu-cacho.png'],
    eyebrow: '3 CREMES, 3 PRIORIDADES', headline: 'Qual combina com seu cabelo ondulado?',
    body: 'Widi para indicação específica de ondas. Salon Line para custo por quantidade. Inoar para uso entre curvaturas diferentes.',
    title: '3 cremes para cabelo ondulado: escolha pela prioridade',
    description: 'Widi Care Ondulando a Juba é a opção mais específica para ondas. Salon Line Definição Natural se destaca pelo custo por quantidade. Inoar Meu Cacho, Meu Crush atende diferentes curvaturas. Compare tamanho, dose e ponto de atenção no guia.',
    alt: 'Embalagens reais de Widi Care Ondulando a Juba, Salon Line Definição Natural e Inoar Meu Cacho Meu Crush em um comparativo vertical.',
    required: ['Widi', 'Salon Line', 'Inoar'],
    cta: 'Compare no guia',
    link: '/artigos/melhores-cremes-para-cabelo-ondulado-sem-pesar/', board: boards.produtos,
    publish: '2026-09-02T12:00:00', local: '02/09/2026 09:00', keywords: 'creme para cabelo ondulado, melhor creme ondulado, Widi Ondulando a Juba, creme sem pesar',
  },
  {
    id: '05', kind: 'photo', theme: 'terracotta', photo: '02-dose-palmas.png', side: 'left', position: 'center 55%',
    eyebrow: 'DOSE PEQUENA PRIMEIRO', headline: 'O creme pesa? Não troque ainda',
    body: 'Espalhe uma porção pequena nas mãos, aplique no comprimento e acrescente somente onde faltar deslizamento.',
    title: 'Creme pesa no cabelo ondulado? Teste a dose antes de trocar',
    description: 'Espalhe uma porção pequena nas duas mãos, aplique no comprimento e nas pontas e só acrescente onde os dedos ainda travarem. Avalie quando o cabelo estiver completamente seco. Salve para lembrar na próxima lavagem.',
    alt: 'Close de duas mãos espalhando uma pequena quantidade de creme ao lado de cabelo ondulado úmido.',
    cta: 'Salve para dosar melhor',
    link: '/artigos/melhores-cremes-para-cabelo-ondulado-sem-pesar/', board: boards.ondas,
    publish: '2026-09-02T16:30:00', local: '02/09/2026 13:30', keywords: 'quanto creme usar cabelo ondulado, creme pesa, finalização sem pesar, ondas finas',
  },
  {
    id: '06', kind: 'guide', theme: 'olive',
    eyebrow: 'ESCOLHA PELO OBJETIVO', headline: 'Creme leve não resolve tudo',
    intro: 'Leia o cabelo seco antes de culpar o pote.',
    rows: [
      ['Falta maciez', 'Priorize deslizamento e desembaraço.'],
      ['A onda some ao secar', 'Talvez falte fixação, não creme.'],
      ['Raiz fica colada', 'Reduza a dose e afaste da raiz.'],
      ['Secagem demora demais', 'Revise a soma de camadas.'],
      ['Pontas pedem ajuda', 'Concentre o creme somente nelas.'],
    ],
    title: 'Cabelo ondulado: qual função está faltando na finalização?',
    description: 'Falta maciez? Procure deslizamento. A onda some seca? Teste fixação. Raiz colada? Reduza a dose. Secagem demorada? Revise as camadas. Pontas ásperas? Concentre o creme nelas. Salve esta árvore de decisão antes de comprar outro pote.',
    alt: 'Árvore de decisão relaciona cinco sinais do cabelo ondulado à função ou ajuste que vale testar.',
    required: ['Falta maciez', 'A onda some ao secar', 'Raiz fica colada', 'Secagem demora demais', 'Pontas pedem ajuda'],
    cta: 'Salve antes de comprar',
    link: '/artigos/melhores-cremes-para-cabelo-ondulado-sem-pesar/', board: boards.ondas,
    publish: '2026-09-02T22:30:00', local: '02/09/2026 19:30', keywords: 'creme cabelo ondulado sem pesar, ondas sem definição, raiz colada, finalização leve',
  },
  {
    id: '07', kind: 'guide', theme: 'plum', compact: true,
    eyebrow: 'ANTES DE ESCOLHER', headline: 'Creme para cacheado: 6 critérios',
    intro: 'O melhor pote depende do seu objetivo, não só da curvatura escrita na embalagem.',
    rows: [
      ['Indicação oficial', 'A marca inclui sua curvatura?'],
      ['Textura', 'Fluida ou densa para a sua rotina?'],
      ['Objetivo', 'Maciez, definição, fitagem ou custo?'],
      ['Dose', 'A embalagem ajuda a repetir a quantidade?'],
      ['Camadas', 'Vai entrar gelatina, óleo ou mousse?'],
      ['Ponto de atenção', 'Há risco de peso ou fixação firme?'],
    ],
    title: 'Como escolher creme para cabelo cacheado sem cair no pote da moda',
    description: 'Confira seis critérios: indicação oficial, textura, objetivo, controle da dose, combinação com outras camadas e ponto de atenção. O melhor creme para cabelo cacheado é o que entrega a função que falta em uma quantidade que o fio tolera. Salve antes de comparar.',
    alt: 'Checklist vertical apresenta seis critérios para escolher creme de pentear para cabelo cacheado.',
    required: ['Indicação oficial', 'Textura', 'Objetivo', 'Dose', 'Camadas', 'Ponto de atenção'],
    cta: 'Salve antes de comparar',
    link: '/artigos/melhores-cremes-de-pentear-para-cabelo-cacheado/', board: boards.cachos,
    publish: '2026-09-03T12:30:00', local: '03/09/2026 09:30', keywords: 'melhor creme cabelo cacheado, escolher creme de pentear, finalização cacheada, creme sem pesar',
  },
  {
    id: '08', kind: 'photo', theme: 'rose', photo: '05-raiz-seca.png', side: 'right', position: 'center 51%',
    eyebrow: 'ESPERE SECAR', headline: 'Raiz colada não pede mais produto',
    body: 'Primeiro reduza a dose e mantenha o creme longe da raiz. Compare uma lavagem por vez.',
    title: 'Raiz colada depois do creme? Faça este teste simples',
    description: 'Se a raiz fica colada depois da secagem, reduza a quantidade e aplique o creme somente no comprimento e nas pontas. Não troque técnica e produto no mesmo dia. Salve para comparar uma lavagem de cada vez.',
    alt: 'Mulher de cabelo ondulado seco observa e levanta suavemente uma pequena área da raiz diante do espelho.',
    cta: 'Salve para testar',
    link: '/artigos/melhores-cremes-de-pentear-para-cabelo-cacheado/', board: boards.cachos,
    publish: '2026-09-03T17:00:00', local: '03/09/2026 14:00', keywords: 'creme pesou cabelo cacheado, raiz colada, cabelo sem volume, dose creme pentear',
  },
  {
    id: '09', kind: 'product', theme: 'blue', products: ['widi-ondulando.png'],
    eyebrow: 'INDICAÇÃO ESPECÍFICA', headline: 'Ondulando a Juba faz sentido para você?',
    body: 'É voltado a ondas e tem modo de uso detalhado. Ainda assim, dose alta e muitas camadas podem pesar.',
    title: 'Widi Care Ondulando a Juba: para quem faz sentido?',
    description: 'O Widi Care Ondulando a Juba 500 ml tem indicação oficial específica para cabelos ondulados e modo de uso por mechas. Faz mais sentido para quem quer começar por um creme pensado para ondas, controlando dose e camadas.',
    alt: 'Embalagem real do Widi Care Ondulando a Juba 500 ml em cartão de decisão para cabelos ondulados.',
    required: ['Ondulando a Juba', 'dose alta', 'camadas'],
    cta: 'Veja os pontos de atenção',
    link: '/artigos/melhores-cremes-para-cabelo-ondulado-sem-pesar/', board: boards.produtos,
    publish: '2026-09-03T23:30:00', local: '03/09/2026 20:30', keywords: 'Widi Care Ondulando a Juba, creme cabelo ondulado, ondas sem pesar, creme 500 ml',
  },
  {
    id: '10', kind: 'guide', theme: 'terracotta',
    eyebrow: 'ORDEM DA FINALIZAÇÃO', headline: 'Creme primeiro, gelatina depois',
    intro: 'A ordem mais simples separa maciez e sustentação.',
    rows: [
      ['1. Cabelo úmido', 'Distribua água por igual.'],
      ['2. Pouco creme', 'Aplique no comprimento e nas pontas.'],
      ['3. Gelatina fina', 'Espalhe por cima sem pentear de novo.'],
      ['4. Amasse', 'Modele as mechas de baixo para cima.'],
      ['5. Espere secar', 'Solte a rigidez somente no final.'],
    ],
    title: 'Gelatina antes ou depois do creme? Salve a ordem correta',
    description: 'A ordem prática é: cabelo úmido por igual, pouco creme, camada fina de gelatina por cima, amassar de baixo para cima, secar sem tocar e soltar a rigidez somente no fim. Salve para seguir na próxima finalização.',
    alt: 'Passo a passo vertical mostra a ordem entre cabelo úmido, creme, gelatina, amassar e secar.',
    required: ['1. Cabelo úmido', '2. Pouco creme', '3. Gelatina fina', '4. Amasse', '5. Espere secar'],
    cta: 'Salve a ordem',
    link: '/artigos/gelatina-antes-ou-depois-do-creme-de-pentear-2026/', board: boards.finalizacao,
    publish: '2026-09-04T11:30:00', local: '04/09/2026 08:30', keywords: 'gelatina antes ou depois do creme, ordem finalização, creme e gelatina, cachos definidos',
  },
  {
    id: '11', kind: 'photo', theme: 'olive', photo: '07-gelatina-mecha.png', side: 'left', position: 'center 52%',
    eyebrow: 'CAMADA FINA', headline: 'Gelatina não precisa encharcar a mecha',
    body: 'Espalhe pouco produto nas mãos, distribua no comprimento e amasse. Só aumente depois de avaliar seco.',
    title: 'Como passar gelatina sem exagerar na quantidade',
    description: 'Espalhe pouca gelatina nas mãos, distribua uma camada fina no comprimento e nas pontas e amasse de baixo para cima. Espere secar antes de decidir se faltou fixação. Salve para testar com menos produto.',
    alt: 'Mulher de cabelo crespo aplica uma camada fina de gelatina em uma única mecha úmida.',
    cta: 'Salve para testar',
    link: '/artigos/gelatina-antes-ou-depois-do-creme-de-pentear-2026/', board: boards.finalizacao,
    publish: '2026-09-04T17:00:00', local: '04/09/2026 14:00', keywords: 'como passar gelatina cabelo, gelatina capilar, excesso gelatina, finalização cacheada',
  },
  {
    id: '12', kind: 'guide', theme: 'rose',
    eyebrow: 'LEIA DEPOIS DE SECO', headline: 'Gelatina: sinal e próximo ajuste',
    intro: 'Rigidez durante a secagem não é a mesma coisa que aspereza persistente.',
    rows: [
      ['Rigidez solta ao amassar', 'Era a camada de fixação.'],
      ['Continua duro', 'Reduza somente a gelatina.'],
      ['Farelo branco', 'Teste os produtos separados.'],
      ['Raiz ficou baixa', 'Afaste a gelatina da raiz.'],
      ['Aspereza permanece', 'Simplifique as camadas na próxima lavagem.'],
    ],
    title: 'Gelatina deixou duro, pesado ou áspero? Veja o próximo ajuste',
    description: 'Rigidez que solta ao amassar é fixação. Dureza persistente pede menos gelatina. Farelo pede testar os produtos separados. Raiz baixa pede distância da raiz. Aspereza que continua pede menos camadas. Salve o diagnóstico para consultar depois.',
    alt: 'Tabela vertical relaciona cinco sinais depois da gelatina ao próximo ajuste de finalização.',
    required: ['Rigidez solta ao amassar', 'Continua duro', 'Farelo branco', 'Raiz ficou baixa', 'Aspereza permanece'],
    cta: 'Salve o diagnóstico',
    link: '/artigos/gelatina-capilar-resseca-cabelo-cacheado/', board: boards.finalizacao,
    publish: '2026-09-04T22:30:00', local: '04/09/2026 19:30', keywords: 'gelatina cabelo duro, gelatina resseca, cabelo cacheado áspero, excesso gelatina',
  },
  {
    id: '13', kind: 'photo', theme: 'blue', photo: '06-gota-oleo.png', side: 'left', position: 'center 52%',
    eyebrow: 'UMA GOTA PRIMEIRO', headline: 'Óleo pesa no cabelo ondulado?',
    body: 'Pode pesar. Espalhe uma gota nas mãos e concentre nas pontas secas, longe da raiz.',
    title: 'Óleo no cabelo ondulado: comece com uma gota',
    description: 'Óleo pode pesar no cabelo ondulado quando a dose sobe ou chega perto da raiz. Comece com uma gota, espalhe bem nas mãos e encoste somente nas pontas secas. Salve para lembrar da dose inicial.',
    alt: 'Close de uma gota de óleo na palma da mão ao lado das pontas de cabelo ondulado seco.',
    cta: 'Salve a dose inicial',
    link: '/artigos/oleo-de-argan-pesa-no-cabelo-ondulado/', board: boards.ondas,
    publish: '2026-09-05T12:30:00', local: '05/09/2026 09:30', keywords: 'óleo cabelo ondulado, óleo pesa, pontas secas, óleo de argan cabelo',
  },
  {
    id: '14', kind: 'product', theme: 'plum', products: ['lola-argan-oil-50ml.webp'],
    eyebrow: 'ÓLEO DE ARGAN 50 ML', headline: 'Quando o Lola Argan Oil faz sentido?',
    body: 'Para testar pouca quantidade nas pontas ou soltar a rigidez depois de seco. Não é convite para cobrir a raiz.',
    title: 'Lola Argan Oil 50 ml: para quem faz sentido?',
    description: 'O Lola Cosmetics Argan Oil 50 ml faz sentido para quem quer testar uma quantidade mínima nas pontas ou usar pouco óleo ao soltar a camada firme depois da secagem. O ponto de atenção é a dose, especialmente em cabelo ondulado fino.',
    alt: 'Embalagem real do Lola Cosmetics Argan Oil 50 ml em cartão de decisão para cabelo ondulado.',
    required: ['Lola Argan Oil', 'pontas', 'raiz'],
    cta: 'Veja como usar sem pesar',
    link: '/artigos/oleo-de-argan-pesa-no-cabelo-ondulado/', board: boards.produtos,
    publish: '2026-09-05T18:00:00', local: '05/09/2026 15:00', keywords: 'Lola Argan Oil 50 ml, óleo de argan cabelo, óleo para pontas, cabelo ondulado fino',
  },
  {
    id: '15', kind: 'guide', theme: 'terracotta',
    eyebrow: 'ONDE O ÓLEO ENTRA', headline: 'Pontas, comprimento ou raiz?',
    intro: 'A área de aplicação muda o risco de peso.',
    rows: [
      ['Pontas secas', 'Comece com uma gota bem espalhada.'],
      ['Comprimento com frizz', 'Use o resíduo das mãos.'],
      ['Raiz oleosa', 'Não acrescente óleo nessa área.'],
      ['Camada firme seca', 'Amasse com mãos secas ou quase sem óleo.'],
      ['Cabelo já pesado', 'Não some outra camada no mesmo dia.'],
    ],
    title: 'Óleo no cabelo ondulado: onde aplicar e onde evitar',
    description: 'Pontas secas: uma gota. Comprimento com frizz: só o resíduo das mãos. Raiz oleosa: não aplique. Camada firme seca: amasse com mãos secas ou quase sem óleo. Cabelo já pesado: não some outra camada. Salve para consultar.',
    alt: 'Mapa de aplicação mostra como usar óleo nas pontas e no comprimento e quando evitar a raiz.',
    required: ['Pontas secas', 'Comprimento com frizz', 'Raiz oleosa', 'Camada firme seca', 'Cabelo já pesado'],
    cta: 'Salve o mapa de aplicação',
    link: '/artigos/oleo-de-argan-pesa-no-cabelo-ondulado/', board: boards.ondas,
    publish: '2026-09-05T23:30:00', local: '05/09/2026 20:30', keywords: 'como usar óleo cabelo ondulado, óleo nas pontas, raiz oleosa, frizz ondulado',
  },
  {
    id: '16', kind: 'photo', theme: 'rose', photo: '03-proteger-ao-dormir.png', side: 'right', position: 'center 48%',
    eyebrow: 'ANTES DE DORMIR', headline: 'Prenda sem esticar os cachos',
    body: 'Faça um coque abacaxi bem frouxo ou use proteção de cetim para reduzir o amassado do day after.',
    title: 'Day after cacheado começa antes de dormir',
    description: 'Para reduzir o amassado do day after, faça um coque abacaxi frouxo, sem esticar a raiz, ou use uma proteção de cetim. No dia seguinte, solte e retoque somente as mechas que perderam a forma. Salve para lembrar à noite.',
    alt: 'Mulher cacheada prende os cachos no alto com um elástico largo de cetim, sem esticar a raiz.',
    cta: 'Salve para lembrar à noite',
    link: '/artigos/como-recuperar-os-cachos-no-day-after-sem-lavar/', board: boards.cachos,
    publish: '2026-09-06T13:00:00', local: '06/09/2026 10:00', keywords: 'day after cacheado, coque abacaxi, proteger cachos dormir, cetim cabelo',
  },
  {
    id: '17', kind: 'guide', theme: 'olive',
    eyebrow: 'DAY AFTER SEM EXCESSO', headline: 'Retocar ou lavar de novo?',
    intro: 'Observe o que aconteceu e escolha a menor intervenção.',
    rows: [
      ['Poucas mechas amassadas', 'Umedeça e modele somente essas áreas.'],
      ['Frizz na camada de cima', 'Use mãos levemente úmidas.'],
      ['Uma mecha esticada', 'Umedeça e enrole no dedo.'],
      ['Perda geral de forma', 'Revise a finalização da próxima lavagem.'],
      ['Peso ou acúmulo', 'Evite novas camadas e considere lavar.'],
    ],
    title: 'Day after cacheado: quando retocar e quando lavar',
    description: 'Poucas mechas amassadas pedem retoque localizado. Frizz no topo pede mãos úmidas. Uma mecha esticada pode ser enrolada no dedo. Perda geral de forma pede rever a rotina. Peso ou acúmulo pedem evitar novas camadas e considerar lavar. Salve o guia.',
    alt: 'Guia vertical relaciona cinco situações de day after ao menor retoque necessário.',
    required: ['Poucas mechas amassadas', 'Frizz na camada de cima', 'Uma mecha esticada', 'Perda geral de forma', 'Peso ou acúmulo'],
    cta: 'Salve o guia de day after',
    link: '/artigos/como-recuperar-os-cachos-no-day-after-sem-lavar/', board: boards.cachos,
    publish: '2026-09-06T17:30:00', local: '06/09/2026 14:30', keywords: 'day after cacheado, recuperar cachos, quando lavar cabelo cacheado, retoque cachos',
  },
  {
    id: '18', kind: 'guide', theme: 'blue',
    eyebrow: 'RETOQUE LOCALIZADO', headline: 'Uma mecha perdeu a curva?',
    intro: 'Não refaça o cabelo inteiro por causa de uma área.',
    rows: [
      ['1. Separe a mecha', 'Não molhe o restante.'],
      ['2. Umedeça', 'Use só água ou pouca bruma.'],
      ['3. Modele', 'Enrole no dedo ou amasse.'],
      ['4. Deixe secar', 'Não puxe nem abra antes da hora.'],
    ],
    title: 'Day after: 4 passos para recuperar uma mecha',
    description: 'Quatro passos: separe a mecha, umedeça somente ela, modele com o dedo ou amasse e deixe secar sem puxar. O retoque localizado evita cobrir todo o cabelo com água e produto. Salve para usar no próximo day after.',
    alt: 'Passo a passo vertical ensina a recuperar uma única mecha no day after sem molhar todo o cabelo.',
    required: ['1. Separe a mecha', '2. Umedeça', '3. Modele', '4. Deixe secar'],
    cta: 'Salve os 4 passos',
    link: '/artigos/como-recuperar-os-cachos-no-day-after-sem-lavar/', board: boards.finalizacao,
    publish: '2026-09-06T23:00:00', local: '06/09/2026 20:00', keywords: 'day after cabelo ondulado, recuperar mecha, retoque localizado, cachos amassados',
  },
  {
    id: '19', kind: 'photo', theme: 'plum', photo: '04-difusor-posicionar.png', side: 'left', position: 'center 49%',
    eyebrow: 'MENOS VENTO SOLTO', headline: 'Posicione antes de ligar',
    body: 'Apoie a mecha no difusor desligado. Ligue por alguns instantes e desligue antes de mudar de área.',
    title: 'Difusor sem bagunçar as ondas: posicione antes de ligar',
    description: 'Coloque a mecha no difusor com o aparelho desligado, ligue por alguns instantes e desligue antes de trocar de área. Isso reduz o vento solto sobre o cabelo. Salve para testar na próxima secagem.',
    alt: 'Mulher ondulada posiciona uma mecha no difusor desligado antes de iniciar a secagem.',
    cta: 'Salve para a próxima secagem',
    link: '/artigos/precisa-usar-protetor-termico-no-difusor/', board: boards.finalizacao,
    publish: '2026-09-07T12:00:00', local: '07/09/2026 09:00', keywords: 'como usar difusor cabelo ondulado, difusor sem frizz, secar ondas, definição cabelo',
  },
  {
    id: '20', kind: 'guide', theme: 'terracotta',
    eyebrow: 'CHECKLIST DO DIFUSOR', headline: '5 passos para secar sem desmontar',
    intro: 'Use o acessório com cuidado e confirme a proteção contra calor no rótulo.',
    rows: [
      ['1. Proteja do calor', 'Use produto com função térmica declarada.'],
      ['2. Escolha morno ou baixo', 'Evite calor e velocidade excessivos.'],
      ['3. Posicione desligado', 'Acomode a mecha antes do vento.'],
      ['4. Seque sem passear', 'Mantenha por instantes em cada área.'],
      ['5. Desligue para trocar', 'Mude de mecha com o aparelho parado.'],
    ],
    title: 'Como usar difusor em cabelo ondulado e cacheado: 5 passos',
    description: 'Cinco passos: proteção térmica declarada, temperatura e velocidade baixas, posicionar a mecha com o aparelho desligado, secar por instantes sem passear e desligar antes de trocar de área. Salve para consultar na próxima secagem.',
    alt: 'Checklist vertical enumera cinco passos para usar difusor em cabelos ondulados e cacheados.',
    required: ['1. Proteja do calor', '2. Escolha morno ou baixo', '3. Posicione desligado', '4. Seque sem passear', '5. Desligue para trocar'],
    cta: 'Salve os 5 passos',
    link: '/artigos/precisa-usar-protetor-termico-no-difusor/', board: boards.finalizacao,
    publish: '2026-09-07T18:30:00', local: '07/09/2026 15:30', keywords: 'difusor cabelo cacheado, como usar difusor, proteção térmica, secar cachos',
  },
  {
    id: '21', kind: 'guide', theme: 'rose',
    eyebrow: 'LEIA O RÓTULO', headline: 'Seu finalizador protege do calor?',
    intro: 'Sem declaração de proteção térmica, não presuma que o creme cumpre essa função.',
    rows: [
      ['Diz proteção térmica', 'Siga a quantidade e o modo de uso.'],
      ['Diz leave-in ou creme', 'Isso sozinho não confirma proteção.'],
      ['Difusor no morno', 'Ainda há exposição ao calor.'],
      ['Difusor no frio', 'A função térmica deixa de ser necessária.'],
      ['Vai somar produtos', 'Prefira camadas finas para não pesar.'],
    ],
    title: 'Protetor térmico no difusor: checklist rápido do rótulo',
    description: 'Procure a declaração de proteção térmica no rótulo. Leave-in ou creme não confirmam essa função sozinhos. No morno ainda há calor; no frio a função térmica deixa de ser necessária. Se somar produtos, use camadas finas. Salve o checklist.',
    alt: 'Checklist vertical explica o que procurar no rótulo antes de usar difusor com calor.',
    required: ['Diz proteção térmica', 'Diz leave-in ou creme', 'Difusor no morno', 'Difusor no frio', 'Vai somar produtos'],
    cta: 'Salve o checklist do rótulo',
    link: '/artigos/precisa-usar-protetor-termico-no-difusor/', board: boards.finalizacao,
    publish: '2026-09-07T23:30:00', local: '07/09/2026 20:30', keywords: 'protetor térmico difusor, leave-in proteção térmica, cabelo cacheado difusor, rótulo finalizador',
  },
];
